services:
  mlflow:
    image: mlflow/mlflow:2.4.0
    container_name: mlflow
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      BACKEND_STORE_URI: postgresql+psycopg2://mlflow:mlflowpass@postgres:5432/mlflow
      ARTIFACT_ROOT: s3://mlflow-artifacts/
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - minio
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri $BACKEND_STORE_URI --default-artifact-root $ARTIFACT_ROOT

  postgres:
    image: postgres:15
    container_name: mlflow-postgres
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflowpass
      POSTGRES_DB: mlflow
    volumes:
      - mlflow-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: mlflow-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - mlflow-minio-data:/data
    restart: unless-stopped

volumes:
  mlflow-postgres-data:
  mlflow-minio-data:

