version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    ports:
      - "8080:80"
    environment:
      PMA_HOST: 192.168.1.95
      PMA_PORT: 3306
      PMA_USER: employees_user
      PMA_PASSWORD: efi-academy

